async function createJpegliModule(moduleArg={}){var Module=moduleArg;var h=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(l){let {createRequire:a}=await import("node:module");var m=a(import.meta.url)}var n=(a,c)=>{throw c;},p=import.meta.url,r="",t,u;if(l){var v=m("node:fs");p.startsWith("file:")&&(r=m("node:path").dirname(m("node:url").fileURLToPath(p))+"/");u=a=>{a=w(a)?new URL(a):a;return v.readFileSync(a)};t=async a=>{a=w(a)?new URL(a):a;return v.readFileSync(a,void 0)};
process.argv.slice(2);n=(a,c)=>{process.exitCode=a;throw c;}}else if(h||k){try{r=(new URL(".",p)).href}catch{}k&&(u=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});t=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var x=console.log.bind(console),z=console.error.bind(console),A,B=!1,w=a=>a.startsWith("file://");class C{}class D extends C{}function E(){if(!G?.buffer?.resizable){var a=
H.buffer;G=new Int8Array(a);Module.HEAPU8=I=new Uint8Array(a);J=new Uint32Array(a)}}function K(a){Module.onAbort?.(a);a=`Aborted(${a})`;z(a);B=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var L;async function M(a){if(!A)try{var c=await t(a);return new Uint8Array(c)}catch{}if(a==L&&A)a=new Uint8Array(A);else if(u)a=u(a);else throw"both async and sync fetching of the wasm failed";return a}async function N(a,c){try{var d=await M(a);return await WebAssembly.instantiate(d,
c)}catch(b){z(`failed to asynchronously prepare wasm: ${b}`),K(b)}}async function O(a){var c=L;if(!A&&!l)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(b){z(`wasm streaming compile failed: ${b}`),z("falling back to ArrayBuffer instantiation")}return N(c,a)}class P{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var G,I,Q=[null,[],[]],S=new TextDecoder,T=(a,c,d,b)=>{d=c+d;if(b)return d;for(;a[c]&&
!(c>=d);)++c;return c},J;Module.print&&(x=Module.print);Module.printErr&&(z=Module.printErr);Module.wasmBinary&&(A=Module.wasmBinary);Module.UTF8ToString=(a,c,d)=>a?S.decode(I.subarray(a,T(I,a,c,d))):"";var U,V,W,H,X,ha={g:()=>K(""),i:()=>{throw new D;},j:a=>{var c=I.length;a>>>=0;if(a>2147483648)return!1;for(var d=1;d<=4;d*=2){var b=c*(1+.2/d);b=Math.min(b,a+100663296);a:{b=(Math.min(2147483648,Math.ceil(Math.max(a,b)/65536)*65536)-H.buffer.byteLength+65535)/65536|0;try{H.grow(b);E();var e=1;break a}catch(f){}e=
void 0}if(e)return!0}return!1},m:a=>{n(a,new P(a))},f:()=>52,k:function(){return 70},d:(a,c,d,b)=>{for(var e=0,f=0;f<d;f++){var Z=J[c>>2],R=J[c+4>>2];c+=8;for(var F=0;F<R;F++){var y=a,g=I[Z+F],q=Q[y];g&&g!==10?q.push(g):(y=y===1?x:z,g=T(q,0),g=S.decode(q.buffer?q.subarray(0,g):new Uint8Array(q.slice(0,g))),y(g),q.length=0)}e+=R}J[b>>2]=e;return 0},e:aa,l:ba,a:ca,h:da,b:ea,c:fa};function ba(a,c,d,b){var e=W();try{return X.get(a)(c,d,b)}catch(f){V(e);if(!(f instanceof C))throw f;U(1,0)}}function aa(a,
c,d){var b=W();try{return X.get(a)(c,d)}catch(e){V(b);if(!(e instanceof C))throw e;U(1,0)}}function ca(a,c){var d=W();try{X.get(a)(c)}catch(b){V(d);if(!(b instanceof C))throw b;U(1,0)}}function fa(a,c,d,b){var e=W();try{X.get(a)(c,d,b)}catch(f){V(e);if(!(f instanceof C))throw f;U(1,0)}}function ea(a,c,d){var b=W();try{X.get(a)(c,d)}catch(e){V(b);if(!(e instanceof C))throw e;U(1,0)}}function da(a,c,d,b){var e=W();try{X.get(a)(c,d,b)}catch(f){V(e);if(!(f instanceof C))throw f;U(1,0)}}var Y;Y=await (async function(){function a(b){b=
Y=b.exports;Module._malloc=b.q;Module._free=b.r;Module._emd_jpegli_last_error=b.s;Module._emd_jpegli_simd_target=b.t;Module._emd_free=b.u;Module._emd_jpegli_encode=b.v;U=b.w;V=b.x;W=b.y;H=b.n;X=b.p;E();return Y}var c={a:ha},d=Module.instantiateWasm;if(d)return new Promise(b=>{d(c,e=>b(a(e)))});L??=Module.locateFile?Module.locateFile?Module.locateFile("jpegli.wasm",r):r+"jpegli.wasm":(new URL("jpegli.wasm",import.meta.url)).href;return function(b){return a(b.instance)}(await O(c))}());await (async function(){B||
Y.o()}());;return Module}export default createJpegliModule;
